
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: lowlighter/metrics 😁
        uses: lowlighter/metrics@latest
        with:
          user: ESMAT001
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_reactions: yes
          plugin_stars: yes
          plugin_stars_limit: 4 # Limit to 4 entries
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_filter: push, issue, pr, review, comment, star
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut, infographile, scripter, forker
          plugin_achievements_limit: 0
